Made sure that PAPI_TOT_CYC is the first event added to multiplexing event set.
This will demonstrate the bug in perf_event multiplexing arithmetic in case5 on MIPS and other perf_event subsystems that likely have some breakage in the kernels handling of multiplexing. The common bug is that the perf_event subsystem does not fill in the second and third elements of the 24 byte read that gets returned from the kernel. These values are time_enabled and time_running. MIPS as of 3.0.3 just fills this in after a HZ tick has happened. Workarounds are pretty simple in the low level layer...

A buggy output looks like this (3.0.3 MIPS/Linux Big Endian)

-bash-4.1$ ./ctests/multiplex1
case1: Does PAPI_multiplex_init() not break regular operation?
Added PAPI_TOT_CYC
Added PAPI_FP_INS
case1: PAPI_TOT_CYC  PAPI_FP_INS
case1:         1843775252     80000000

case2: Does setmpx/add work?
Added PAPI_TOT_CYC
Added PAPI_FP_INS
case2: PAPI_TOT_CYC  PAPI_FP_INS
case2:         1843773254     80000037

case3: Does add/setmpx work?
Added PAPI_TOT_CYC
Added PAPI_FP_INS
case3: PAPI_TOT_CYC  PAPI_FP_INS
case3:         1843772919     80000037

case4: Does add/setmpx/add work?
Added PAPI_TOT_CYC
Added PAPI_FP_INS
case4: PAPI_TOT_CYC  PAPI_FP_INS
case4:         1843773959     80000037

case5: Does setmpx/add/add/start/read work?
Added PAPI_TOT_CYC
Added PAPI_FP_INS
read @start counter[0]: 9223372034707292159
read @stop  counter[0]: 1843784577
difference  counter[0]: -9223372032863507582
 multiplex1.c                           FAILED
Line # 389
Error: Difference in start and stop resulted in negative value!