lmsensors: Avoid possible overruns on local variable
The local path_name variable in link_lmsensors_libraries() needs to
be PATH_MAX in size to avoid possible overruns and scribbling over
parts of the stack.

 Error: OVERRUN (CWE-119): [#def22] [important]
 papi-7.2.0b1-build/papi-7.2.0b1/src/components/lmsensors/linux-lmsensors.c:398:7: overrun-buffer-arg: Overrunning array "path_name" of 1024 bytes by passing it to a function which accesses it at byte offset 4095 using argument "4096UL". [Note: The source code implementation of the function has been overridden by a builtin model.]
 #  396|      // Step 3: Try the explicit install default.
 #  397|      if (dl1 == NULL && lmsensors_root != NULL) {                          // if root given, try it.
 #  398|->       snprintf(path_name, PATH_MAX, "%s/lib64/libsensors.so", lmsensors_root);   // PAPI Root check.
 #  399|         dl1 = dlopen(path_name, RTLD_NOW | RTLD_GLOBAL);             // Try to open that path.
 #  400|      }

 Error: OVERRUN (CWE-119): [#def23] [important]
 papi-7.2.0b1-build/papi-7.2.0b1/src/components/lmsensors/linux-lmsensors.c:404:7: overrun-buffer-arg: Overrunning array "path_name" of 1024 bytes by passing it to a function which accesses it at byte offset 4095 using argument "4096UL". [Note: The source code implementation of the function has been overridden by a builtin model.]
 #  402|      // Step 4: Try another explicit install default.
 #  403|      if (dl1 == NULL && lmsensors_root != NULL) {                          // if root given, try it.
 #  404|->       snprintf(path_name, PATH_MAX, "%s/lib/libsensors.so", lmsensors_root);   // PAPI Root check.
 #  405|         dl1 = dlopen(path_name, RTLD_NOW | RTLD_GLOBAL);             // Try to open that path.
 #  406|      }