Update libpfm4, to be current with the following commits: --------------------------------------------------------------
commit fa84c27b60572621a8e48e364de9f55bdff5237e
Author: Andreas Beckmann <a.beckmann@fz-juelich.de>
Date:   Wed Dec 4 23:53:35 2019 +0100

    fix incorrect strncpy() usage

    gcc 9 failed on mips* with:
    /usr/include/mips64el-linux-gnuabi64/bits/string_fortified.h:106:10: error: ‘__builtin___strncpy_chk’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
    pfmlib_mips.c: In function ‘pfm_mips_detect’:
    pfmlib_mips.c:147:2: note: length computed here
      147 |  strncpy(pfm_mips_cfg.model,buffer,strlen(buffer));

    strncpy(dest, src, strlen(src)) does *not* copy the terminating '\0'
    strncpy(dest, src, strlen(src)+1) is identical to strcpy(dest, src)
    but the third argument to strncpy() should rather be based on the size
    of 'dest', not 'src'

    Signed-off-by: Andreas Beckmann <a.beckmann@fz-juelich.de>

commit c3e97e0c9510f047623f6548cdef188eed0038cd
Author: Andreas Beckmann <a.beckmann@fz-juelich.de>
Date:   Sun Apr 22 12:56:02 2018 +0200

    fix typos and normalize spacing

    most typos were found by Lintian

    Signed-off-by: Andreas Beckmann <a.beckmann@fz-juelich.de>

commit de4beb0da7530bc1dcd2f19582dfeca2ecb1d185
Author: Stephane Eranian <eranian@gmail.com>
Date:   Fri Sep 25 11:41:56 2020 -0700

    update AMD Fam17h Zen2 event table

    Based on PPR version 0.91 Sep1, 2020.

    Thanks to Emmanuel for tracking the diffs.

    Signed-off-by: Stephane Eranian <eranian@gmail.com>

commit 53797b096497dd278fa844c302ce93495b469754
Author: Stephane Eranian <eranian@gmail.com>
Date:   Fri Sep 25 11:08:51 2020 -0700

    update Intel Icelake event table to 1.09

    This patch updates the Icelake event table based on the official
    JSON event file up to version 1.09.

    Signed-off-by: Stephane Eranian <eranian@gmail.com>

commit 414e482ace00d334015341e032a8b325d80e92eb
Author: Stephane Eranian <eranian@gmail.com>
Date:   Wed Sep 23 16:59:57 2020 -0700

    update to version 4.11.1

    Update to 4.11.1 revision to fix some minor issues with 11.0 release

    Signed-off-by: Stephane Eranian <eranian@gmail.com>

commit dfe30a72c18dc64ea8e55c469a9adcfec9c09340
Author: Stephane Eranian <eranian@gmail.com>
Date:   Wed Sep 23 16:53:53 2020 -0700

    install Fujitsu A64FX man page in ARM64 mode

    This patch corrects the documentation Makefile to install
    the libpfm_a64fx.3 man page when bulding for ARM64. Otherwise
    the man page woul only be installed in ARM (32-bit) mode.

    Reported-by: William Cohen <wcohen@redhat.com>
    Signed-off-by: Stephane Eranian <eranian@gmail.com>

commit 3a7dbd35cfde80923dca3d7a02386fde6d859f93
Author: Stephane Eranian <eranian@gmail.com>
Date:   Wed Sep 2 11:40:42 2020 -0700

    update to version 4.11.0

    Update to 4.11.0 revision to prepare for release

    Signed-off-by: Stephane Eranian <eranian@gmail.com>