shlib.c: Check for NULL
Thanks to Will Cohen for reporting.
Coverity picked up an instance of a value that could be NULL and strlen
would barf on it.

Error: FORWARD_NULL (CWE-476):
papi-5.2.0/src/ctests/shlib.c:70: var_compare_op: Comparing "shinfo->map" to null implies that "shinfo->map" might be null.
papi-5.2.0/src/ctests/shlib.c:74: var_deref_model: Passing "shinfo" to function "print_shlib_info_map(PAPI_shlib_info_t const *)", which dereferences null "shinfo->map".
papi-5.2.0/src/ctests/shlib.c:13:26: var_assign_parm: Assigning: "map" = "shinfo->map".
papi-5.2.0/src/ctests/shlib.c:24:3: deref_var_in_call: Function "strlen(char const *)" dereferences an offset off "map" (which is a copy of "shinfo->map").