infiniband: Ensure that memory allocated by strdup() freed
It is possible in add_ib_counter() that one of the strdup() operations
fails and the other succeeds.  In cases where the struct referencing
them is being free because of a failure one of the strdup() any
allocated memory should be freed also.  This was noted noted in a
coverity scan of PAPI:

 Error: RESOURCE_LEAK (CWE-772):
 papi-7.2.0b1-build/papi-7.2.0b1/src/components/infiniband/linux-infiniband.c:332:5: alloc_fn: Storage is returned from allocation function "strdup".
 papi-7.2.0b1-build/papi-7.2.0b1/src/components/infiniband/linux-infiniband.c:332:5: var_assign: Assigning: "new_cnt->ev_file_name" = storage returned from "strdup(file_name)".
 papi-7.2.0b1-build/papi-7.2.0b1/src/components/infiniband/linux-infiniband.c:338:9: leaked_storage: Freeing "new_cnt" without freeing its pointer field "ev_file_name" leaks the storage that "ev_file_name" points to.
 #  336|       {
 #  337|           PAPIERROR("cannot allocate memory for counter internal fields");
 #  338|->         papi_free(new_cnt);
 #  339|           return (0);
 #  340|       }

 Error: RESOURCE_LEAK (CWE-772):
 papi-7.2.0b1-build/papi-7.2.0b1/src/components/infiniband/linux-infiniband.c:331:5: alloc_fn: Storage is returned from allocation function "strdup".
 papi-7.2.0b1-build/papi-7.2.0b1/src/components/infiniband/linux-infiniband.c:331:5: var_assign: Assigning: "new_cnt->ev_name" = storage returned from "strdup(name)".
 papi-7.2.0b1-build/papi-7.2.0b1/src/components/infiniband/linux-infiniband.c:338:9: leaked_storage: Freeing "new_cnt" without freeing its pointer field "ev_name" leaks the storage that "ev_name" points to.
 #  336|       {
 #  337|           PAPIERROR("cannot allocate memory for counter internal fields");
 #  338|->         papi_free(new_cnt);
 #  339|           return (0);
 #  340|       }