libpfm4: update to commit 52632c7
Original commits:

    commit 52632c7ffe3b088846e86ced207e38dfe5bc4731
    Author: Stephane Eranian <eranian@gmail.com>
    Date:   Mon May 1 22:40:05 2023 -0700

        add Intel EmeraldRapid core PMU support

        Intel EmeraldRapid shares the same PMU as Intel SapphireRapid.
        Add an emr:: PMU sharing the same event table.

        Signed-off-by: Stephane Eranian <eranian@gmail.com>

    commit 1befa3d200cc17d5a278fcb2f597c4876c58f949
    Author: Stephane Eranian <eranian@gmail.com>
    Date:   Tue Apr 25 00:35:41 2023 -0700

        fix AMD Zen3/Zen4 detection

        To cover more models of Zen4.

        Signed-off-by: Stephane Eranian <eranian@gmail.com>

    commit 8ea5575b6b10a91f3d7a079ca35d6e4eb33f379d
    Author: William Cohen <wcohen@redhat.com>
    Date:   Fri Apr 14 16:34:58 2023 -0700

        Fix unitialized variable in gen_tracepoint_table()

        Need to ensure that p was initialized at the start of function
        gen_tracepoint_table otherwise on some architectures such as s390x
        will get the following error when compiling with -Werror:

            make[1]: Entering directory '/root/rpmbuild/BUILD/libpfm-4.13.0/lib'
            cc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -
    Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1
     -m64 -march=z14 -mtune=z15 -fasynchronous-unwind-tables -fstack-clash-protection -g -Wall -Werror -Wextra -Wno-unused-parameter -I. -I/root/rp
    mbuild/BUILD/libpfm-4.13.0/lib/../include -DCONFIG_PFMLIB_DEBUG -DCONFIG_PFMLIB_OS_LINUX -D_REENTRANT -I. -fvisibility=hidden -DCONFIG_PFMLIB_A
    RCH_S390X -I. -c pfmlib_perf_event_pmu.c
            pfmlib_perf_event_pmu.c: In function 'gen_tracepoint_table':
            pfmlib_perf_event_pmu.c:434:35: error: 'p' may be used uninitialized in this function [-Werror=maybe-uninitialized]
              434 |                         p->modmsk = 0;
                  |                         ~~~~~~~~~~^~~
            cc1: all warnings being treated as errors

        Signed-off-by: William Cohen <wcohen@redhat.com>

    commit 72709ed4237e9259348080e05ffd7750ee202506
    Author: Stephane Eranian <eranian@gmail.com>
    Date:   Wed Apr 12 18:05:35 2023 -0700

        fix active list ordering issue

        In commit
                363825f72afd ("maintain list of active PMUs")

        We introduce an active list of PMUs to speed up lookups of events.
        However, there was a bug introduced by this commit which caused
        wrong encodings of certain events. For instance, on Intel x86,
        the event unhalted_reference_cycles was encoded using an architected
        event code instead of the model specific event code which used a fixed
        counter. This was due to the fact that the ordering of the PMU models
        in pfmlib_pmus[] was inverted by the way we built the active list. The
        order in the table matters for lookups. the list must maintain the same
        order. This patch fixes the problem by rewriting the linked list code
        to support appending to the tail of the list (instead of the head).
        That way the order in the table is maintained.

        The patch introduces the notion of a link list node supporting a
        double linked list data structure with basic accessor functions.

        Signed-off-by: Stephane Eranian <eranian@gmail.com>

    commit aa31ca87eb00d0f74d5566fed9a7cf62c48e236a
    Author: Stephane Eranian <eranian@gmail.com>
    Date:   Tue Apr 11 11:12:02 2023 -0700

        Revert "optimize active PMU list further"

        This reverts commit b009b1263098eec925bc2dba1760c70d8a46d4b8.

        Because it makes it necessary to have a lock as the head of the
        list may be changing at each encoding and that would cause issues
        with multiple parallel calls of the encoding entry points.

        This optimization will be redone with a thread local variiable
        once we modify libpfm4 to depend on libpthread.

        Signed-off-by: Stephane Eranian <eranian@gmail.com>

    commit 80260a02ab805acfb702ee3eab9af82729f20c79
    Author: Ian Rogers <irogers@google.com>
    Date:   Fri Apr 7 14:27:23 2023 -0700

        clear pfmlib_active_pmus_list on init and terminate

        Must clear on pfm_terminate() to avoid creating cycles in the list
        in case pfm_initialize() is called multiple times.
        Also clear in pfm_initialize() to make sure we start from a known
        situation.

        Signed-off-by: Ian Rogers <irogers@google.com>

    commit 9c3d167fa6017836cb6e33004471cebd4d1bf0f6
    Author: Stephane Eranian <eranian@gmail.com>
    Date:   Thu Apr 6 01:23:45 2023 -0700

        fix active PMU list handling for LIBPFM_ENCODE_INACTIVE=1

        There was an issue introduced by:
         363825f72afd ("maintain list of active PMUs")

        Where if a PMU is not detected because not exported by OS, it would
        not be put on the active list when LIBPFM_ENCODE_INACTIVE=1 causing
        tests/validate on some uncore PMU events.

        Fix this by correctly handling the case where a PMU is not exported
        by the OS.

        Also check that a PMU is actually active in pfmlib_terminate() and
        pfm_get_pmu_by_type() again to handle LIBPFM_ENCODE_INACTIVE=1.

        Signed-off-by: Stephane Eranian <eranian@gmail.com>

    commit b009b1263098eec925bc2dba1760c70d8a46d4b8
    Author: Stephane Eranian <eranian@gmail.com>
    Date:   Thu Mar 30 22:07:15 2023 -0700

        optimize active PMU list further

        By moving the last PMU matched to the head of the list each time an
        event is found in pfmlib_parse_event().

        Signed-off-by: Stephane Eranian <eranian@gmail.com>

    commit 363825f72afde0e8cae2ecfd261a95d2bd0b3868
    Author: Stephane Eranian <eranian@gmail.com>
    Date:   Wed Mar 29 19:55:58 2023 -0700

        maintain list of active PMUs

        Given that the list of PMUs supported per architecture keeps growing,
        it is becoming expensive to iterate over each PMU looking for a
        match. The macro pfmlib_for_each_pmu() is iterating over active and
        inactive PMUs looking for active ones. Given that the number of inactive
        PMUs is always larger than the number of active, this was expensive.

        Fix this by creating a list of active PMUs and adding a new macro
        pfmlib_for_each_active_pmu(). We use a oubly linked list to allow
        further optimizations.

        As an example on a X86 build, the new iterator allowed a 10x reduction
        in iterations inside pfmlib_parse_event() for a core PMU event.

        When LIBPFM_ENCODE_INACTIVE is set to 1, then all PMUs supported by
        the architecture are put on the active list even when they are not
        detected. This simplifies the parsing loop.

        Signed-off-by: Stephane Eranian <eranian@gmail.com>

    commit b3e956879bc9499d5c3012f3f82ce31d2f169e5b
    Author: Stephane Eranian <eranian@gmail.com>
    Date:   Wed Mar 29 22:04:57 2023 -0700

        Fix parsing of LIBPFM_ENCODE_INACTIVE

        Was not taking into account the value of the variable, unlike
        for LIBPFM_DEBUG and LIBPFM_VERBOSE. Passing LIBPFM_ENCODE_INACTIVE=0
        would still activate the feature.

        Signed-off-by: Stephane Eranian <eranian@gmail.com>

    commit 158c879b9408b84ecfc78c1385c81ce25a8f2cd1
    Author: Namhyung Kim <namhyung@google.com>
    Date:   Wed Mar 29 19:27:19 2023 -0700

        Use relative path using openat(2) in gen_tracepoint_table()

        It doesn't need to traverse the filesystem hierarchy from the root.
        Instead it can use relative pathname with openat() and pass it to
        fdopendir().  Actually it can introduce some kernel lock contentions
        when it's invoked from multiple CPUs at the same time.

        Signed-off-by: Namhyung Kim <namhyung@google.com>

    commit f200f50751557a1b9aef6120140bfb13d7cafe9f
    Author: Namhyung Kim <namhyung@google.com>
    Date:   Wed Mar 29 19:06:25 2023 -0700

        Define HAS_OPENAT for Linux

        Now I think all major Linux distro provides openat() functions in libc as
        it's specified in POSIX.1-2008.  Maybe we could add a config check to
        detect them later if somebody don't.

        Also remove the old code to undefine the macro unconditionally.

        Signed-off-by: Namhyung Kim <namhyung@google.com>

    commit 3d77461cb966259c51f3b3e322564187f4bef7fb
    Author: Stephane Eranian <eranian@gmail.com>
    Date:   Tue Mar 28 16:48:58 2023 -0700

        Update to version 4.13.0

        Various updates and AMD Zen4 support.

        Signed-off-by: Stephane Eranian <eranian@gmail.com>