Update libpfm4 Current with commit 92c52017d7395c4040ec22949ee8c7f17bc5b4f7 Author: Stephane Eranian <eranian@gmail.com> Date:   Sat Jun 22 09:17:23 2024 -0700
    add missing pfmlib_intel_gnr.c file

    To complete the Intel GraniteRapids support.
    Was missing from commit 23d0b7c47c2e ("add Intel GraniteRapids core PMU support")
    Sorry about that.
    Signed-off-by: Stephane Eranian <eranian@gmail.com>

commit 44a55dd97c929087b4ca93540f6bbb2d2efffd15
Author: Thomas Richter <tmricht@linux.ibm.com>
Date:   Tue Jun 18 10:17:27 2024 +0200

    s390: Fix calloc compiler error for gcc14

    The definition of calloc is as follows:
        void *calloc(size_t nmemb, size_t size);
    number of members is in the first parameter and the
    size is in the second parameter.

    Fix error message on the gcc 14 20240102:
      error: 'calloc' sizes specified with 'sizeof' in the earlier
      argument and not in the later argument ...
    by adhering to the calloc() calling convention.

    Output before:
     # make
     Entering directory '/root/perfmon2-libpfm4/lib'
     cc  -g -Wall -Werror -Wextra -Wno-unused-parameter -I. \
             -I/root/perfmon2-libpfm4/lib/../include -DCONFIG_PFMLIB_DEBUG \
             -DCONFIG_PFMLIB_OS_LINUX -DCONFIG_PFMLIB_NOTRACEPOINT \
             -DHAS_OPENAT -D_REENTRANT -I. -fvisibility=hidden \
             -DCONFIG_PFMLIB_ARCH_S390X -I. -c pfmlib_s390x_cpumf.c
     pfmlib_s390x_cpumf.c: In function ‘pfm_cpumcf_init’:
     pfmlib_s390x_cpumf.c:221:26: error: ‘calloc’ sizes specified with \
             ‘sizeof’ in the earlier argument and not in the later argument \
             [-Werror=calloc-transposed-args]
      221 | cpumcf_pe = calloc(sizeof(*cpumcf_pe), cfvn_set_count):
          |                          ^
     pfmlib_s390x_cpumf.c:221:26: note: earlier argument should specify
            number of elements, later size of each element

    Signed-off-by: Thomas Richter <tmricht@linux.ibm.com>
    Acked-by: Sumanth Korikkar <sumanthk@linux.ibm.com>

commit 23d0b7c47c2ec06334b3eb378bfc3568b08e0042
Author: Stephane Eranian <eranian@gmail.com>
Date:   Mon Jun 3 23:10:45 2024 -0700

    add Intel GraniteRapids core PMU support

    Based on JSON event files published on github.com/Intel/perfmon
    version 1.02, dated 05/10/2024

    Signed-off-by: Stephane Eranian <eranian@gmail.com>

commit 489a940be48980956b27dda89de1eb91b01f185d
Author: Stephane Eranian <eranian@gmail.com>
Date:   Fri Jun 21 21:24:34 2024 -0700

    fix Intel SPR inst_retired umask flags

    Were missing PEBS and fixed event code umask (ANY) was not encoded
    properly.

    inst_retired.any -> fixed counter 0 encoding 0x100
    inst_retired.any_p -> generic counter encoding 0x00c0

    Signed-off-by: Stephane Eranian <eranian@gmail.com>

commit ace21560113100f4ab5032e99753459ed9da7049
Author: Stephane Eranian <eranian@gmail.com>
Date:   Wed Jun 19 23:32:25 2024 -0700

    fix validate_x86.c Intel SPR/EMR inst_retired tests

    They were not using the proper event codes for the different
    versions of inst_retired.

    Signed-off-by: Stephane Eranian <eranian@gmail.com>

Note: Built PAPI with Intel Xeon Gold 6430 (SPR) with GCC 14. No errors
occured during build. Unable to test Granite Rapids support due to the
PAPI team not having access to a machine with Granite Rapids. Unable to
test instr_retired fixes due to no access to Emerald Rapids and events
not available on Sapphire Rapids machine we have access to.