net: Ensure that strings copied are NULL terminated
The strncpy function may not put a NULL at the end of the destination
buffer if the source string is longer than the specified copy size.
To ensure that the the copied strings are null terminated using
snprintf instead and checking its return value to ensure that the
copied string was not truncated.  The snprintf function will always
include a NULL at the end of copy.  This particular fix addresses the
following two coverity issues:

Error: BUFFER_SIZE (CWE-170): [#def6]
papi-7.0.1/src/components/net/linux-net.c:346: buffer_size_warning: Calling "strncpy" with a maximum size argument of 128 bytes on destination array "_net_native_events[i].name" of size 128 bytes might leave the destination string unterminated.

Error: BUFFER_SIZE (CWE-170): [#def7]
papi-7.0.1/src/components/net/linux-net.c:347: buffer_size_warning: Calling "strncpy" with a maximum size argument of 128 bytes on destination array "_net_native_events[i].description" of size 128 bytes might leave the destination string unterminated.