testlib: give better error message if component failed to initialize
Old message:

./zero
test_utils.c                           FAILED
Line # 697
Error: Zero Counters Available!  PAPI Won't like this!

New message:

./zero

Component perf_event disabled due to Error initializing libpfm4
test_utils.c                           FAILED
Line # 702
Error: ERROR! Zero Counters Available!